### ISSUE TITLE
atom beta 1.2 term3 rebuild error

### ISSUE THREAD

**Issue by mibac** [Floobits/atom-term3#11]
Mac OS X 10.10.5
Xcode 7.1
term3 fails to rebuild with atom 1.2 beta-0
does rebuild with atom 1.1.0
after rebuild with attom 1.1.0 it works in 1.2 beta-0
lost the npm-debug.log

**Comment by kans** [comment]
@mibac 
I'm using term3 with 1.2.  Are you still having this problem?

**Comment by kans** [comment]
@mibac 
Is it possible you updated xcode?  If so, you need to open Xcode and agree to the new license.

**Comment by adamvaughan** [comment]
It builds fine with release versions of Atom. The problem seems to only happen when using beta versions.

<img width="727" alt="screen shot 2015-11-16 at 4 52 15 pm" src="https://cloud.githubusercontent.com/assets/472854/11198547/c358e38c-8c82-11e5-80e8-50d47fb3d5c0.png">

The `*** No rule to make target '../../../../../../../../../../../../Applications/Atom'` output seems suspicious. Perhaps something isn't handling the space in the application directory (Atom Beta.app).

**Comment by kans** [comment]
> Perhaps something isn't handling the space 

Could be... presumably atom itself has to compile native modules too.  I wonder what the difference is?

**Comment by mibac** [comment]
It works ok with Atom 1.2 stable that was released a few days ago.
